[package]
name = "lfg-studio/analytics"
version = "1.1.10"
description = "A wrapper for the GameAnalytics SDK"
license = "Apache-2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["dig1t"]

include = ["src", "default.project.json"]
exclude = ["src/**/*.spec.luau"]

[dependencies]
Promise = "evaera/promise@4.0.0"
GameAnalytics = "dig1t/gameanalytics-sdk@2.2.86"
